-- Add new columns to leads table for audit assumptions
ALTER TABLE leads ADD COLUMN IF NOT EXISTS maps_url TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS avg_ticket_value INTEGER DEFAULT 5000;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS leads_per_month INTEGER DEFAULT 20;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS historical_leads_count INTEGER DEFAULT 0;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS response_time TEXT DEFAULT '1-4 hrs';
ALTER TABLE leads ADD COLUMN IF NOT EXISTS crm_name TEXT;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS crm_active BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS follow_up_attempts INTEGER DEFAULT 2;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS missed_calls_percentage INTEGER DEFAULT 20;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS review_response_active BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS email_marketing_active BOOLEAN DEFAULT false;
ALTER TABLE leads ADD COLUMN IF NOT EXISTS has_chat_widget BOOLEAN DEFAULT false;